/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
export type { Lock } from "./Lock";
export type { MemeFactory } from "./MemeFactory";
export type { PreSale } from "./PreSale";
export type { TokenTemplate } from "./TokenTemplate";
