/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPreSale,
  IPreSaleInterface,
} from "../../../contracts/interface/IPreSale";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "ownerBuy",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountToken",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "buyDate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "BuyTokenEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "priceToken",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amountSellToken",
        type: "uint256",
      },
    ],
    name: "PreSaleCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "priceToken",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountSellToken",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "createPreSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPreSale__factory {
  static readonly abi = _abi;
  static createInterface(): IPreSaleInterface {
    return new Interface(_abi) as IPreSaleInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPreSale {
    return new Contract(address, _abi, runner) as unknown as IPreSale;
  }
}
